version: "3.9"
services:
  api:
    build:
      context: ./api/rental_movie
      dockerfile: docker/Dockerfile
      target: develop
    volumes:
      - ./api/rental_movie/:/src
    working_dir: "/src"
    tty: true
    ports: 
      - "3000:3000"
    restart: always
    depends_on:
      - db
    command: ["uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "3000"]

  db:
    image: mysql:8.0.27
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: movie
      MYSQL_DATABASE: movie
      MYSQL_USER: movie
      MYSQL_PASSWORD: movie
      TZ: "Asia/Tokyo"
    ports:
      - "13306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d

volumes:
  db_data:

networks:
  app-net:
    driver: bridge