"""remove fee

Revision ID: 27574384bf77
Revises: 92c24611b4a6
Create Date: 2024-05-05 05:30:22.942539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '27574384bf77'
down_revision: Union[str, None] = '92c24611b4a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rentals', 'fee')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rentals', sa.Column('fee', mysql.INTEGER(), autoincrement=False, nullable=False, comment='料金'))
    # ### end Alembic commands ###
