"""change rental type

Revision ID: d1ac04ef7fc5
Revises: 27574384bf77
Create Date: 2024-05-05 05:43:48.032078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd1ac04ef7fc5'
down_revision: Union[str, None] = '27574384bf77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('value', sa.Enum('NEW_RELEASE', 'SEMI_NEW_RELEASE', 'OLD_RELEASE', name='rentaltype'), nullable=False, comment='レンタルタイプ'))
    op.drop_column('movies', 'rental_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('rental_type', mysql.ENUM('NEW_RELEASE', 'SEMI_NEW_RELEASE', 'OLD_RELEASE'), nullable=False, comment='レンタルタイプ'))
    op.drop_column('movies', 'value')
    # ### end Alembic commands ###
